<a href="https://colab.research.google.com/github/arkincognito/PyTorch/blob/main/01_Pytorch_Tensor_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

# Device Setup

In [ ]:
device = torch.device("cuda")
model = TheModelClass(*args, **kwargs)
# 사용할 GPU 장치 번호를 선택합니다. 
model.load_state_dict(torch.load(PATH, map_location="cuda:0")) 
model.to(device) # 모델에서 사용하는 input Tensor들은 input = input.to(device) 을 호출해야 합니다.

#Tensor manipulation

## 1D Tensor

In [ ]:
t1 = torch.FloatTensor([1., 2., 3., 4., 5., 6.])

In [ ]:
print(t1.dim()) #Dimension
print(t1.size()) #Size
print(t1.shape) #Size
print(t1[:2]) #Slicing
print(t1[::2]) #Slicing
# print(t[-1::-1]) #This doesn't work
print(t1[0], t1[1], t1[2]) #Index

1
torch.Size([6])
torch.Size([6])
tensor([1., 2.])
tensor([1., 3., 5.])
tensor(1.) tensor(2.) tensor(3.)


t[-1::-1] doesn't work in Pytorch. Python list takes negative values for strides, but Pytorch doesn't

In [ ]:
arr = [1., 2., 3., 4., 5., 6.]
arr[-1::-1]

[6.0, 5.0, 4.0, 3.0, 2.0, 1.0]

##2D Tensor

In [ ]:
t2 = torch.FloatTensor([[0., 1., 2.],
                       [3., 4., 5.],
                       [6., 7., 8.],
                       [9., 1.1, 1.2]])

In [ ]:
print(t2.dim()) #Dimension
print(t2.size()) #Size
print(t2.shape) #Size
print(t2[:2]) #Slicing
print(t2[::2]) #Slicing
print(t2[2][:-1])
print(t2[:-1][1])
print(t2[0], t2[1], t2[2][1]) #Index

2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([[0., 1., 2.],
        [6., 7., 8.]])
tensor([6., 7.])
tensor([3., 4., 5.])
tensor([0., 1., 2.]) tensor([3., 4., 5.]) tensor(7.)


#Broadcasting

## Vectors of same Shape

In [ ]:
t1 = torch.FloatTensor([1,2])
t2 = torch.FloatTensor([3,4])
t1+t2

tensor([4., 6.])

## Vector + Scalar

In [ ]:
t1 = torch.FloatTensor([1,2])
t2 = torch.FloatTensor([3])
t1+t2

tensor([4., 5.])

## Vectors of same Dimension

In [ ]:
t1 = torch.FloatTensor([[1,2,3]])
t2 = torch.FloatTensor([[3],[4]])
print(t1.shape)
print(t2.shape)
print(t1+t2)

torch.Size([1, 3])
torch.Size([2, 1])
tensor([[4., 5., 6.],
        [5., 6., 7.]])


Last ojperate broadcasts the shape [1,3] and [2,1] into [2,3], [2,3].

#Multiplication vs Matrix Multiplication

In [ ]:
t1 = torch.FloatTensor([[1,2]]) #shape [1,2] -> broadcast into [2,2]
t2 = torch.FloatTensor([[3],[4]]) #shape [2,1] -> broadcast into [2,2]
print(t1.mul(t2)) # Element-wise Multiplication
print(t1*t2) # Element-wise Multiplication

tensor([[3., 6.],
        [4., 8.]])
tensor([[3., 6.],
        [4., 8.]])


$m1 = 
\begin{pmatrix}
1 & 2\\
\end{pmatrix},\space
m2 = \begin{pmatrix}
3 \\
4 \\
\end{pmatrix}
$
<br><br>
m1.mul(m2) broadcasts m1 and m2 into <br><br>
$m1 = 
\begin{pmatrix}
1 & 2\\
1 & 2\\
\end{pmatrix},\space
m2 = \begin{pmatrix}
3 & 3\\
4 & 4\\
\end{pmatrix}
$
<br><br>
and does element-wise multiplication resulting in <br><br>
$m1.mul(m2) = 
\begin{pmatrix}
3 & 6\\4 & 8\\
\end{pmatrix}
$

In [ ]:
t1 = torch.FloatTensor([[1,2]]) #shape [1,2]
t2 = torch.FloatTensor([[3],[4]]) #shape [2,1]
print(t1.matmul(t2)) # Matrix Multiplication
print(t1.mm(t2)) # Matrix Multiplication

tensor([[11.]])
tensor([[11.]])


$m1 = 
\begin{pmatrix}
1 & 2\\
\end{pmatrix},\space
m2 = \begin{pmatrix}
3 \\
4 \\
\end{pmatrix}
$
<br><br>
$m1.matmul(m2) = m1\times m2
= \begin{pmatrix}
1 \times 3 + 2 \times 4
\end{pmatrix}
=
\begin{pmatrix}
3 + 8
\end{pmatrix}
=
\begin{pmatrix}
11
\end{pmatrix}
$

#Mean

In [ ]:
t = torch.FloatTensor([[[1,2], [3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(t.mean())
print(t.mean(dim=0)) #Mean by 0th dimension
print(t.mean(dim=1)) #Mean by 1st dimension
print(t.mean(dim=-1)) #Mean by last dimension

tensor(6.5000)
tensor([[5., 6.],
        [7., 8.]])
tensor([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.]])
tensor([[ 1.5000,  3.5000],
        [ 5.5000,  7.5000],
        [ 9.5000, 11.5000]])


#Sum

In [ ]:
t = torch.FloatTensor([[[1,2], [3,4]],
                       [[5,6], [7,8]],
                       [[9,10],[11,12]]
                       ])
print(t.sum())
print(t.sum(dim=0)) #Sum by 0th dimension
print(t.sum(dim=1)) #Sum by 1st dimension
print(t.sum(dim=-1)) #Sum by last dimension

tensor(78.)
tensor([[15., 18.],
        [21., 24.]])
tensor([[ 4.,  6.],
        [12., 14.],
        [20., 22.]])
tensor([[ 3.,  7.],
        [11., 15.],
        [19., 23.]])


# Max & Argmax

In [ ]:
t = torch.FloatTensor([[1,2], [4,3]])
print(t.max()) #Max on the whole tensor
print(t.max(dim=0)) #Max on 0th dimension. Returns max and argmax
print(t.max(dim=1)) #Max on 1th dimension. Returns max and argmax

tensor(4.)
torch.return_types.max(
values=tensor([4., 3.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 0]))


# View(Reshape)

In [ ]:
t = np.array([[[1,2], [3,4]],
              [[5,6], [7,8]],
              [[9,10],[11,12]]
              ])
ft = torch.FloatTensor(t)
ft.shape

torch.Size([3, 2, 2])

In [ ]:
print(ft.view(-1,2))
print(ft.view(-1,2).shape)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])
torch.Size([6, 2])


In [ ]:
print(ft.view(-1, 2, 3))
print(ft.view(-1, 2, 3).shape)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])
torch.Size([2, 2, 3])


#Squeeze(Flatten)
If the dimension length is 1, then squeeze out the dimension.

In [ ]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [ ]:
ft = torch.FloatTensor([[0,1],[2,3],[4,5]])
print(ft.shape)
print(ft.squeeze())
print(ft.squeeze().shape)

torch.Size([3, 2])
tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])
torch.Size([3, 2])


In [ ]:
ft = torch.FloatTensor([[[0]],[[1]],[[2]]])
print(ft.shape)
print(ft.squeeze())
print(ft.squeeze().shape)

torch.Size([3, 1, 1])
tensor([0., 1., 2.])
torch.Size([3])


In [ ]:
ft = torch.FloatTensor([[[0]],[[1]],[[2]]])
print(ft.shape)
print(ft.squeeze(dim=2))
print(ft.squeeze(dim=2).shape)

torch.Size([3, 1, 1])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
ft = torch.FloatTensor([[[0, 1]],[[1,2]],[[2,3]]])
print(ft.shape)
print(ft.squeeze(dim=1))
print(ft.squeeze(dim=1).shape)

torch.Size([3, 1, 2])
tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])
torch.Size([3, 2])


#Unsqueeze(dim)

In [ ]:
ft = torch.FloatTensor([0,1,2])
ft.shape

torch.Size([3])

In [ ]:
print(ft.unsqueeze(dim=0))
print(f'unsqueeze(dim=0).shape: {ft.unsqueeze(dim=0).shape}')
print(ft.unsqueeze(dim=1))
print(f'unsqueeze(dim=1).shape: {ft.unsqueeze(dim=1).shape}')
print(ft.unsqueeze(dim=0).unsqueeze(dim=-1))
print(f'unsqueeze(dim=-1).shape: {ft.unsqueeze(dim=-1).shape}')

tensor([[0., 1., 2.]])
unsqueeze(dim=0).shape: torch.Size([1, 3])
tensor([[0.],
        [1.],
        [2.]])
unsqueeze(dim=1).shape: torch.Size([3, 1])
tensor([[[0.],
         [1.],
         [2.]]])
unsqueeze(dim=-1).shape: torch.Size([3, 1])


# Type Casting

In [ ]:
lt = torch.LongTensor([1,2,3,4])
print(lt)
print(lt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [ ]:
bt = torch.BoolTensor([True, False, False, True])
print(bt)
print(bt.float())
print(bt.long())

tensor([ True, False, False,  True])
tensor([1., 0., 0., 1.])
tensor([1, 0, 0, 1])


In [ ]:
bt = lt==3
print(bt)
print(bt.float())
print(bt.long())

tensor([False, False,  True, False])
tensor([0., 0., 1., 0.])
tensor([0, 0, 1, 0])


# Concatenate

In [ ]:
m1 = torch.IntTensor([[1,2],[3,4]])
m2 = torch.IntTensor([[5,6],[7,8]])
print(torch.cat([m1, m2])) # Default dim = 0.
print(torch.cat([m1, m2], dim=0)) # concat within dimension 0
print(torch.cat([m1, m2], dim=1)) # concat within dimension 1

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]], dtype=torch.int32)
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]], dtype=torch.int32)


# Stack
stack([tensors]) stack tensors along new dimension.
If a dimension is given, the new stack extends into that dimension.

In [ ]:
m1 = torch.IntTensor([1,2])
m2 = torch.IntTensor([3,4])
m3 = torch.IntTensor([5,6])
print(torch.stack([m1, m2, m3]))
print(torch.stack([m1, m2, m3], dim=0)) # This is identical to the line below.
print(torch.cat([m1.unsqueeze(0), m2.unsqueeze(0), m3.unsqueeze(0)], dim=0))
print(torch.stack([m1, m2, m3], dim=1)) # This is identical to the line below.
print(torch.cat([m1.unsqueeze(1), m2.unsqueeze(1), m3.unsqueeze(1)], dim=1))

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32)
tensor([[1, 3, 5],
        [2, 4, 6]], dtype=torch.int32)
tensor([[1, 3, 5],
        [2, 4, 6]], dtype=torch.int32)


unsqueeze(0) makes tensor of [1,2] -> concat dim=0 will make [3,2].

# Ones, Zeros

In [ ]:
m1 = torch.IntTensor([[1,2,5],[3,4,6]])
print(torch.zeros_like(m1))
print(torch.ones_like(m1))

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


Tensor shape may vary on the device's gpu.<br>
To match tensor shape, use ones_like() and zeros_like().

# In-Place Operation: postfix _

In [ ]:
m1 = torch.FloatTensor([[1,2],[3,4]])
print(m1.mul(2))
print(f'm1 = {m1}')
print(m1.mul_(2))
print(f'm1 = {m1}')
print(m1.unsqueeze_(dim=1))
print(f'm1 = {m1}')
print(m1.squeeze_())
print(f'm1 = {m1}')

tensor([[2., 4.],
        [6., 8.]])
m1 = tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
m1 = tensor([[2., 4.],
        [6., 8.]])
tensor([[[2., 4.]],

        [[6., 8.]]])
m1 = tensor([[[2., 4.]],

        [[6., 8.]]])
tensor([[2., 4.],
        [6., 8.]])
m1 = tensor([[2., 4.],
        [6., 8.]])
